language: ruby

rvm:
  - 1.9.3

sudo: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install wget curl jq
  - wget https://s3-eu-west-1.amazonaws.com/gossiperl-cdn/gossiperl-1.0.0_all.deb
  - sudo dpkg -i gossiperl-1.0.0_all.deb
  - sudo /etc/gossiperl/start-and-wait.sh
  - sudo /etc/gossiperl/test-overlay.sh

script: bundle exec shindont tests

notifications:
  email: false